version: '3.9'
services:
  db:
    image: spartakode/sqlite3
    volumes:
      - ./sqlite.db:/code/db.sqlite3

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
